### ISSUE TITLE
floating point widthPercent value for the chart give wrong result!!

### ISSUE THREAD

**Issue by AleeAwan** [fusioncharts/fusioncharts-dist#4] opened 2018-10-24 14:27 UTC
I am using marimekko chart in my project and I am giving widthPercent values for my categories to a decimal percision of 2 points as its a business requirement. Issue i have noticed is that if the numbers don't add upto to exact 100 amount like if its 100.00000001 ( its an issue in javascript that floating point numbers sometimes dont add up correctly like 0.1 + 0.2 is not 0.3 ) then bar widths are auto calculated instead of using the one's that i provided?

**Comment by siawo** [comment] 2019-12-03 07:02
@AleeAwan Can you please provide a sample to replicate the problem?

**Comment by AyanBhadury** [comment] 2020-12-15 07:56
> I am using marimekko chart in my project and I am giving widthPercent values for my categories to a decimal percision of 2 points as its a business requirement. Issue i have noticed is that if the numbers don't add upto to exact 100 amount like if its 100.00000001 ( its an issue in javascript that floating point numbers sometimes dont add up correctly like 0.1 + 0.2 is not 0.3 ) then bar widths are auto calculated instead of using the one's that i provided?

@AleeAwan  Please share a demo as requested else we would close the issue considering the problem is solved.

**Comment by AleeAwan** [comment] 2020-12-20 15:33
This issue was opened long ago while i was working for a company which i no
longer work for. You guys can close this issue.

**Closed** 2021-06-03 08:48 UTC
Labels: fixed
